INSERT INTO TODO (ID, TITLE, DONE, DEADLINE, USERNAME) VALUES (101,'spring course',false,CURRENT_DATE(),'gaurav');
INSERT INTO TODO (ID, TITLE, DONE, DEADLINE, USERNAME) VALUES (102,'DSA course',false,CURRENT_DATE(),'gaurav');
INSERT INTO TODO (ID, TITLE, DONE, DEADLINE, USERNAME) VALUES (103,'LLD course',false,CURRENT_DATE(),'gaurav');